# Generated by Django 5.1.1 on 2024-09-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('degree', models.CharField(max_length=20)),
            ],
        ),
    ]
